/* SIGNAL — 한국어 데이터. UI 문자열과 문항 138개.
 * 로직은 ../99shared/signal.app.js 에 있다.
 *
 * 주의: 출처가 미국 조사인 문항은 "미국인"이라고 못 박아 뒀다. 그냥 "사람들"로
 * 옮기면 수치가 거짓이 된다. 원문(영어판)과 id·answer·source 는 1:1로 같다.
 */
window.SIGNAL_DATA = {
  lang: 'ko',
  strings: {
    percent: '퍼센트',
    cancel: '취소',
    tagline: '통계 맞히기 파티 게임',
    subtitle: '사람을 얼마나 잘 아십니까?',
    hostGame: '방 만들기',
    joinGame: '참가하기',
    homeFoot: '인터넷 필요 없음 · 2~8명 · 10라운드',
    back: '← 뒤로',
    yourCode: '내 게임 코드',
    copied: '✓ 복사됨',
    copyCode: '코드 복사',
    step1: '친구들에게 이 코드를 알려 주세요',
    step2: '모두가 같은 코드를 입력합니다',
    step3: '시작을 누르면 — 전원이 같은 10문제를 받습니다',
    startGame: '게임 시작 →',
    enterCode: '게임 코드 입력',
    joinTitle: '게임 참가',
    askHost: '방장에게 4글자 코드를 물어보세요',
    lettersOnly: '알파벳만 · I 와 L 제외',
    joinCta: '참가하기 →',
    lockIn: '확정 →',
    lockTitle: '이 답으로 확정할까요?',
    lockBody: (v) => `${v}% 로 답합니다. 확정한 뒤에는 바꿀 수 없습니다.`,
    lockConfirm: (v) => `${v}% 로 제출`,
    quitTitle: '게임을 그만둘까요?',
    quitBody: '지금까지 한 것은 사라집니다.',
    quitConfirm: '그만두기',
    roundOf: (n) => `10라운드 중 ${n}라운드`,
    theAnswer: '정답',
    yourGuess: '내 답',
    accuracy: '정확도',
    lockedIn: '답이 확정되었습니다',
    tapReveal: '눌러서 정답 보기',
    waitAll: '모두가 제출할 때까지 기다리세요',
    roundScore: '라운드 점수',
    nextRound: (n) => `${n}라운드 →`,
    seeFinal: '최종 점수 보기 →',
    gameComplete: '게임 종료',
    rankOracle: '예언자',
    rankSignal: '시그널',
    rankAnalyst: '분석가',
    rankObserver: '관찰자',
    rankStatic: '잡음',
    outOf: (n) => `${n}점 만점`,
    breakdown: '라운드별 기록',
    roundN: (n) => `${n}라운드`,
    guessShort: '내 답:',
    answerShort: '정답:',
    accShort: '정확도:',
    playAgain: '같은 코드로 다시 하기',
    mainMenu: '처음으로',
  },
  questions: [
  { id:1,  text:"인형이나 애착 물건을 안고 자는 성인은 몇 퍼센트일까?", answer:46, source:"YouGov, 2023" },
  { id:2,  text:"비행기에서 영화를 보다가 운 적이 있는 사람은 몇 퍼센트일까?", answer:55, source:"Gatwick Airport Study, 2022" },
  { id:3,  text:"자기 운전 실력이 평균 이상이라고 믿는 운전자는 몇 퍼센트일까?", answer:93, source:"AAA Foundation, 2018" },
  { id:4,  text:"화장실에서 휴대폰을 쓰는 사람은 몇 퍼센트일까?", answer:74, source:"Verizon Consumer Survey, 2022" },
  { id:5,  text:"일어난 지 5분 안에 휴대폰을 확인하는 사람은 몇 퍼센트일까?", answer:80, source:"IDC Research, 2023" },
  { id:6,  text:"순전히 궁금해서 반려동물 사료를 맛본 적 있는 성인은 몇 퍼센트일까?", answer:18, source:"ASPCA Survey, 2021" },
  { id:7,  text:"직장에 가장 친한 친구가 있다고 답한 직장인은 몇 퍼센트일까?", answer:30, source:"Gallup Workplace, 2023" },
  { id:8,  text:"먹기 전에 몰래 음식 냄새를 맡아 보는 사람은 몇 퍼센트일까?", answer:71, source:"YouGov, 2022" },
  { id:9,  text:"진정한 사랑을 만나 봤다고 믿는 성인은 몇 퍼센트일까?", answer:62, source:"Pew Research Center, 2022" },
  { id:10, text:"말 섞기 싫어서 아는 사람을 못 본 척한 적 있는 사람은 몇 퍼센트일까?", answer:83, source:"YouGov, 2023" },
  { id:11, text:"반려동물이 말을 다 알아듣는 것처럼 대화하는 성인은 몇 퍼센트일까?", answer:67, source:"Harris Poll, 2023" },
  { id:12, text:"안 읽은 책을 읽었다고 거짓말한 적 있는 사람은 몇 퍼센트일까?", answer:42, source:"YouGov, 2022" },
  { id:13, text:"자기 번호 말고 전화번호를 하나라도 외우고 있는 사람은 몇 퍼센트일까?", answer:54, source:"Kaspersky Lab, 2022" },
  { id:14, text:"바닥에 떨어진 음식을 먹어 본 적 있는 성인은 몇 퍼센트일까?", answer:87, source:"YouGov, 2023" },
  { id:15, text:"받은 선물을 그대로 남에게 넘긴 적 있는 사람은 몇 퍼센트일까?", answer:38, source:"YouGov, 2022" },
  { id:16, text:"인터넷에 자기 이름을 검색해 본 적 있는 사용자는 몇 퍼센트일까?", answer:57, source:"Pew Research Center, 2013" },
  { id:17, text:"귀신의 존재를 믿는 미국인은 몇 퍼센트일까?", answer:41, source:"YouGov, 2021" },
  { id:18, text:"호텔 방에서 뭔가를 가져온 적이 한 번이라도 있다고 인정한 투숙객은 몇 퍼센트일까?", answer:87, source:"Passport-Photo.Online, 2023" },
  { id:19, text:"샤워하면서 노래를 부르는 미국인은 몇 퍼센트일까?", answer:37, source:"Harris Poll, 2024" },
  { id:20, text:"끊은 헬스장 회원권을 한 번도 안 쓰는 비율은 몇 퍼센트일까?", answer:67, source:"RunRepeat, 2023" },
  { id:21, text:"이력서에 거짓을 적었다고 인정한 미국인은 몇 퍼센트일까?", answer:33, source:"ResumeBuilder.com, 2022" },
  { id:22, text:"엉뚱한 사람에게 문자를 잘못 보낸 적 있는 사람은 몇 퍼센트일까?", answer:70, source:"Consumer Survey, 2015" },
  { id:23, text:"아직도 어둠이 무섭다고 답한 성인은 몇 퍼센트일까?", answer:29, source:"Talker Research, 2023" },
  { id:24, text:"죽음보다 사람들 앞에서 말하는 게 더 무섭다고 답한 미국인은 몇 퍼센트일까?", answer:40, source:"Communication Research Reports, 2012" },
  { id:25, text:"길에 떨어진 1센트 동전을 줍겠다고 답한 미국인은 몇 퍼센트일까?", answer:56, source:"YouGov, 2018" },
  { id:26, text:"결혼식에서 울었다고 인정한 하객은 몇 퍼센트일까?", answer:40, source:"AP-NORC / WeTV, 2018" },
  { id:27, text:"공공장소에서 모르는 사람의 대화를 일부러 엿듣는다고 인정한 사람은 몇 퍼센트일까?", answer:25, source:"YouGov UK, 2021" },
  { id:28, text:"옷을 빨지 말지 냄새를 맡아 정한다고 인정한 영국인은 몇 퍼센트일까?", answer:83, source:"Philips Survey, 2024" },
  { id:29, text:"여러 사이트에 같은 비밀번호를 돌려 쓰는 사람은 몇 퍼센트일까?", answer:65, source:"Google / Harris Poll, 2019" },
  { id:30, text:"집에 있는 화분에 말을 거는 사람은 몇 퍼센트일까?", answer:27, source:"YouGov, 2018" },
  { id:31, text:"운전 중에 휴대폰을 쓴다고 인정한 운전자는 몇 퍼센트일까?", answer:69, source:"AAA Foundation for Traffic Safety, 2019" },
  { id:32, text:"지금의 연인을 온라인에서 만난 미국인은 몇 퍼센트일까?", answer:39, source:"Pew Research Center, 2019" },
  { id:33, text:"10분짜리 평범한 대화에서 거짓말을 한 번 이상 하는 사람은 몇 퍼센트일까?", answer:60, source:"UMass Amherst / Personality & Social Psych Bulletin, 2002" },
  { id:34, text:"드라마 한 시즌을 하루에 다 몰아 본 적 있는 성인은 몇 퍼센트일까?", answer:64, source:"YouGov, 2018" },
  { id:35, text:"문신이 하나 이상 있는 미국 성인은 몇 퍼센트일까?", answer:32, source:"Pew Research Center, 2023" },
  { id:36, text:"반려동물을 침실에서 재우는 미국인 반려인은 몇 퍼센트일까?", answer:81, source:"American Pet Products Association, 2021-22" },
  { id:37, text:"소개팅 앱이나 온라인 데이팅을 한 번이라도 써 본 미국인은 몇 퍼센트일까?", answer:43, source:"Pew Research Center, 2023" },
  { id:38, text:"매일 커피를 마시는 미국인은 몇 퍼센트일까?", answer:63, source:"National Coffee Association, 2023" },
  { id:39, text:"SNS 에서 가족을 차단하거나 친구 끊은 적 있는 미국인은 몇 퍼센트일까?", answer:30, source:"Pew Research Center, 2018" },
  { id:40, text:"우주 어딘가에 지적 생명체가 있다고 믿는 미국인은 몇 퍼센트일까?", answer:56, source:"Pew Research Center, 2021" },
  { id:41, text:"멀쩡한데 아프다고 하고 결근한 적 있다고 인정한 정규직은 몇 퍼센트일까?", answer:52, source:"CareerBuilder Survey, 2017" },
  { id:42, text:"지난 1년 안에 비디오 게임을 한 미국 성인은 몇 퍼센트일까?", answer:47, source:"Pew Research Center, 2024" },
  { id:43, text:"한밤중에 깨서 휴대폰을 확인하는 성인은 몇 퍼센트일까?", answer:51, source:"Deloitte Digital Consumer Trends, 2022" },
  { id:44, text:"같은 꿈을 반복해서 꿔 본 적 있는 미국인은 몇 퍼센트일까?", answer:62, source:"YouGov, 2022" },
  { id:45, text:"공공장소에서 아는 사람을 일부러 피한 적 있다고 답한 사람은 몇 퍼센트일까?", answer:55, source:"YouGov, 2022" },
  { id:46, text:"전화 통화보다 문자가 낫다고 답한 사람은 몇 퍼센트일까?", answer:58, source:"OpenMarket Consumer Survey, 2016" },
  { id:47, text:"돈이 삶의 큰 스트레스 원인이라고 답한 미국인은 몇 퍼센트일까?", answer:72, source:"APA Stress in America, 2022" },
  { id:48, text:"집 안 온도 설정을 두고 다툰 적 있다고 답한 커플은 몇 퍼센트일까?", answer:55, source:"Harris Poll / Nest, 2018" },
  { id:49, text:"하루 중 아무 날이나 잡았을 때 패스트푸드를 먹는 미국 성인은 몇 퍼센트일까?", answer:37, source:"CDC / NCHS, 2018" },
  { id:50, text:"새해 결심을 끝까지 지키는 데 성공하는 사람은 몇 퍼센트일까?", answer:8, source:"University of Scranton / J. Clinical Psychology, 2002" },
  { id:51, text:"미국 밖으로 한 번도 나가 본 적 없는 미국인은 몇 퍼센트일까?", answer:65, source:"U.S. Travel Association / Statista, 2019" },
  { id:52, text:"천국이 있다고 믿는다고 답한 미국인은 몇 퍼센트일까?", answer:73, source:"Gallup, 2022" },
  { id:53, text:"비행기 타는 것이 무섭다고 답한 미국인은 몇 퍼센트일까?", answer:25, source:"Gallup, 2001" },
  { id:54, text:"지난 한 달 안에 졸음운전을 한 적 있다고 답한 운전자는 몇 퍼센트일까?", answer:41, source:"AAA Foundation for Traffic Safety, 2021" },
  { id:55, text:"매일 탄산음료를 마시는 미국 성인은 몇 퍼센트일까?", answer:30, source:"Gallup, 2012" },
  { id:56, text:"수정헌법 제1조가 보장하는 다섯 가지 권리를 전부 말할 수 있는 미국인은 몇 퍼센트일까?", answer:4, source:"Annenberg Public Policy Center, 2018" },
  { id:57, text:"아침 아닌 끼니로 시리얼을 먹는다고 답한 미국인은 몇 퍼센트일까?", answer:79, source:"YouGov, 2019" },
  { id:58, text:"처음 만나기 전에 그 사람을 검색해 본 적 있는 사람은 몇 퍼센트일까?", answer:78, source:"Harris Poll, 2020" },
  { id:59, text:"운이라는 게 있다고 믿는다고 답한 미국인은 몇 퍼센트일까?", answer:54, source:"Gallup, 2003" },
  { id:60, text:"지난 1년 안에 난폭운전 충동을 느꼈다고 답한 미국 운전자는 몇 퍼센트일까?", answer:80, source:"AAA Foundation for Traffic Safety, 2019" },
  { id:61, text:"말 걸리기 싫어서 통화하는 척한 적 있다고 인정한 사람은 몇 퍼센트일까?", answer:54, source:"YouGov, 2021" },
  { id:62, text:"메일에서 '전체 답장'을 실수로 눌러 본 적 있다고 인정한 직장인은 몇 퍼센트일까?", answer:49, source:"Adobe Email Usage Survey, 2018" },
  { id:63, text:"뱀이 무섭다고 답한 미국인은 몇 퍼센트일까?", answer:40, source:"Gallup, 2001" },
  { id:64, text:"점성술이나 별자리 운세를 챙겨 보는 미국인은 몇 퍼센트일까?", answer:29, source:"Pew Research Center, 2018" },
  { id:65, text:"하루 중 아무 날이나 잡았을 때 아침을 거르는 미국 성인은 몇 퍼센트일까?", answer:25, source:"CDC / USDA, 2020" },
  { id:66, text:"양말을 신고 자는 미국인은 몇 퍼센트일까?", answer:19, source:"YouGov, 2019" },
  { id:67, text:"어제 낮잠을 잤다고 답한 미국 성인은 몇 퍼센트일까?", answer:34, source:"Pew Research Center, 2009" },
  { id:68, text:"평소에 외로움을 느낀다고 답한 미국인은 몇 퍼센트일까?", answer:45, source:"Cigna / Ipsos Loneliness Index, 2020" },
  { id:69, text:"고양이파보다 개파에 가깝다고 답한 미국인은 몇 퍼센트일까?", answer:57, source:"YouGov, 2021" },
  { id:70, text:"불면증을 겪어 본 적 있는 미국 성인은 몇 퍼센트일까?", answer:44, source:"Gallup, 2024" },
  { id:71, text:"현재 유효한 여권을 가진 미국인은 몇 퍼센트일까?", answer:42, source:"U.S. State Department, 2022" },
  { id:72, text:"스트레스를 받으면 단것을 먹는다고 답한 사람은 몇 퍼센트일까?", answer:63, source:"American Psychological Association, 2013" },
  { id:73, text:"간헐적 단식을 해 봤다고 답한 미국인은 몇 퍼센트일까?", answer:28, source:"YouGov, 2022" },
  { id:74, text:"지금 직장에 만족한다고 답한 미국 직장인은 몇 퍼센트일까?", answer:73, source:"Gallup Workplace, 2023" },
  { id:75, text:"매일 격한 운동을 한다고 답한 미국인은 몇 퍼센트일까?", answer:23, source:"Gallup, 2023" },
  { id:76, text:"하루도 빠짐없이 이불을 개는 미국인은 몇 퍼센트일까?", answer:27, source:"YouGov, 2019" },
  { id:77, text:"이웃 대부분의 이름을 모른다고 답한 미국인은 몇 퍼센트일까?", answer:43, source:"Pew Research Center, 2019" },
  { id:78, text:"평소 코를 곤다고 답한 미국 성인은 몇 퍼센트일까?", answer:36, source:"American Academy of Sleep Medicine, 2020" },
  { id:79, text:"진료 전에 담당 의사를 검색해 봤다고 답한 사람은 몇 퍼센트일까?", answer:72, source:"Software Advice Medical Practice Survey, 2020" },
  { id:80, text:"정신건강 치료나 상담을 받아 본 적 있다고 답한 미국인은 몇 퍼센트일까?", answer:39, source:"APA Stress in America, 2023" },
  { id:81, text:"속상할 때 찾는 특정 음식이 있다고 답한 성인은 몇 퍼센트일까?", answer:92, source:"Harris Poll, 2022" },
  { id:82, text:"욕조 목욕보다 샤워가 낫다고 답한 미국인은 몇 퍼센트일까?", answer:61, source:"YouGov, 2021" },
  { id:83, text:"스스로를 내향적이라고 여기는 미국 성인은 몇 퍼센트일까?", answer:44, source:"YouGov, 2022" },
  { id:84, text:"결혼 생활이 '매우 행복하다'고 답한 미국 기혼자는 몇 퍼센트일까?", answer:31, source:"Gallup, 2023" },
  { id:85, text:"싱크대 앞에 서서 한 끼를 통째로 먹어 본 적 있다고 답한 사람은 몇 퍼센트일까?", answer:54, source:"YouGov, 2022" },
  { id:86, text:"일주일에 한 번 이상 스트레스에 짓눌린다고 답한 미국인은 몇 퍼센트일까?", answer:63, source:"APA Stress in America, 2022" },
  { id:87, text:"아침형보다 저녁형 인간이라고 답한 미국인은 몇 퍼센트일까?", answer:66, source:"YouGov, 2022" },
  { id:88, text:"재미없는 걸 알면서도 드라마를 끝까지 다 봤다고 답한 사람은 몇 퍼센트일까?", answer:67, source:"YouGov, 2020" },
  { id:89, text:"평소 잠이 부족하다고 답한 사람은 몇 퍼센트일까?", answer:63, source:"Gallup, 2022" },
  { id:90, text:"소개받자마자 상대 이름을 까먹은 적 있다고 인정한 사람은 몇 퍼센트일까?", answer:71, source:"YouGov, 2023" },
  { id:91, text:"노래·소설 같은 창작을 시도해 본 적 있는 미국 성인은 몇 퍼센트일까?", answer:58, source:"YouGov, 2022" },
  { id:92, text:"일과 삶의 균형을 위해 연봉을 깎아도 좋다고 답한 미국인은 몇 퍼센트일까?", answer:77, source:"FlexJobs Survey, 2022" },
  { id:93, text:"퀴즈 게임 중에 몰래 검색해 본 적 있다고 인정한 성인은 몇 퍼센트일까?", answer:73, source:"YouGov, 2023" },
  { id:94, text:"혼자 있을 때 이유 없이 운 적 있다고 인정한 사람은 몇 퍼센트일까?", answer:49, source:"YouGov, 2023" },
  { id:95, text:"물건에 부딪히고 나서 사과한 적 있다고 답한 사람은 몇 퍼센트일까?", answer:33, source:"YouGov, 2022" },
  { id:96, text:"중요한 대화를 머릿속으로 미리 연습한다고 답한 성인은 몇 퍼센트일까?", answer:74, source:"YouGov, 2023" },
  { id:97, text:"화분을 키우다 실수로 죽여 본 적 있다고 답한 사람은 몇 퍼센트일까?", answer:57, source:"YouGov, 2022" },
  { id:98, text:"카페나 식당 직원에게 가짜 이름을 댄 적 있다고 답한 미국인은 몇 퍼센트일까?", answer:22, source:"YouGov, 2019" },
  { id:99, text:"TV나 영상에 대고 소리 내어 대꾸한 적 있다고 인정한 사람은 몇 퍼센트일까?", answer:74, source:"YouGov, 2023" },
  { id:100, text:"여럿이 둘러앉아 밥 먹는 중에 휴대폰을 한 번이라도 본 적 있다고 답한 사람은 몇 퍼센트일까?", answer:40, source:"Pew Research Center, 2015" },
  { id:101, text:"전 세계에서 스마트폰을 가진 사람은 몇 퍼센트일까?", answer:84, source:"Statista, 2023" },
  { id:102, text:"자동차 타이어를 한 번도 갈아 본 적 없는 사람은 몇 퍼센트일까?", answer:73, source:"AAA Foundation for Traffic Safety, 2022" },
  { id:103, text:"개보다 고양이가 좋다고 답한 미국인은 몇 퍼센트일까?", answer:38, source:"American Pet Products Association, 2023" },
  { id:104, text:"뼈가 부러져 본 적이 한 번도 없는 사람은 몇 퍼센트일까?", answer:74, source:"American Academy of Orthopedic Surgeons, 2023" },
  { id:105, text:"휴대폰 대신 실제 알람 시계를 쓰는 사람은 몇 퍼센트일까?", answer:23, source:"National Sleep Foundation, 2023" },
  { id:106, text:"벌에 한 번도 쏘여 본 적 없는 사람은 몇 퍼센트일까?", answer:45, source:"Entomological Society of America, 2022" },
  { id:107, text:"캠핑을 한 번도 가 본 적 없는 미국인은 몇 퍼센트일까?", answer:51, source:"National Park Service Outdoor Survey, 2023" },
  { id:108, text:"휘파람을 불 줄 아는 사람은 몇 퍼센트일까?", answer:67, source:"Berklee College of Music Survey, 2022" },
  { id:109, text:"자전거를 한 번도 타 본 적 없는 사람은 몇 퍼센트일까?", answer:8, source:"U.S. Department of Transportation, 2023" },
  { id:110, text:"바닐라보다 초코 아이스크림이 좋다고 답한 사람은 몇 퍼센트일까?", answer:71, source:"International Ice Cream Association, 2023" },
  { id:111, text:"비행기를 한 번도 타 본 적 없는 미국인은 몇 퍼센트일까?", answer:19, source:"Airlines for America, 2023" },
  { id:112, text:"무릎을 안 굽히고 발끝에 손이 닿는 사람은 몇 퍼센트일까?", answer:43, source:"American Council on Exercise, 2022" },
  { id:113, text:"가능하면 엘리베이터보다 계단을 택한다고 답한 사람은 몇 퍼센트일까?", answer:31, source:"CDC Physical Activity Survey, 2023" },
  { id:114, text:"박물관에 한 번도 가 본 적 없는 미국인은 몇 퍼센트일까?", answer:26, source:"American Alliance of Museums, 2023" },
  { id:115, text:"전자책보다 종이책이 좋다고 답한 독자는 몇 퍼센트일까?", answer:58, source:"Publishers Weekly Reader Survey, 2023" },
  { id:116, text:"악기를 한 번도 다뤄 본 적 없는 사람은 몇 퍼센트일까?", answer:47, source:"National Association of Music Merchants, 2022" },
  { id:117, text:"수동 변속기 차를 운전할 줄 아는 미국인은 몇 퍼센트일까?", answer:18, source:"National Highway Traffic Safety Administration, 2023" },
  { id:118, text:"전문 마사지를 한 번도 받아 본 적 없는 미국인은 몇 퍼센트일까?", answer:69, source:"American Massage Therapy Association, 2023" },
  { id:119, text:"수영을 제대로 할 줄 아는 사람은 몇 퍼센트일까?", answer:56, source:"American Red Cross, 2023" },
  { id:120, text:"매장보다 온라인 쇼핑이 좋다고 답한 사람은 몇 퍼센트일까?", answer:61, source:"National Retail Federation, 2023" },
  { id:121, text:"사무실 출근보다 재택근무가 좋다고 답한 직장인은 몇 퍼센트일까?", answer:73, source:"Bureau of Labor Statistics, 2023" },
  { id:122, text:"크루즈 여행을 한 번도 가 본 적 없는 미국인은 몇 퍼센트일까?", answer:81, source:"Cruise Lines International Association, 2023" },
  { id:123, text:"스쿠버 다이빙을 한 번도 해 본 적 없는 미국인은 몇 퍼센트일까?", answer:91, source:"Professional Association of Diving Instructors, 2023" },
  { id:124, text:"카드보다 현금 결제가 좋다고 답한 미국인은 몇 퍼센트일까?", answer:27, source:"Federal Reserve Bank Payment Study, 2023" },
  { id:125, text:"카지노에 한 번도 가 본 적 없는 미국인은 몇 퍼센트일까?", answer:52, source:"American Gaming Association, 2023" },
  { id:126, text:"승마를 한 번도 해 본 적 없는 미국인은 몇 퍼센트일까?", answer:74, source:"American Horse Council, 2023" },
  { id:127, text:"출퇴근길에 음악보다 팟캐스트를 듣는 사람은 몇 퍼센트일까?", answer:32, source:"Edison Research Infinite Dial, 2023" },
  { id:128, text:"극장보다 집에서 영화 보는 게 좋다고 답한 사람은 몇 퍼센트일까?", answer:71, source:"Motion Picture Association, 2023" },
  { id:129, text:"스키나 스노보드를 한 번도 타 본 적 없는 미국인은 몇 퍼센트일까?", answer:76, source:"National Ski Areas Association, 2023" },
  { id:130, text:"종이 신문보다 온라인으로 뉴스 보는 게 좋다고 답한 사람은 몇 퍼센트일까?", answer:83, source:"Pew Research Center, 2023" },
  { id:131, text:"번지점프를 한 번도 해 본 적 없는 미국인은 몇 퍼센트일까?", answer:96, source:"Adventure Sports Industry Association, 2023" },
  { id:132, text:"조용한 것보다 배경음악을 틀고 일하는 게 좋다고 답한 사람은 몇 퍼센트일까?", answer:62, source:"Occupational Psychology Research, 2022" },
  { id:133, text:"요가 수업에 한 번도 가 본 적 없는 미국인은 몇 퍼센트일까?", answer:58, source:"Yoga Alliance Research, 2023" },
  { id:134, text:"SNS 에서 나이를 속인 적 있는 사람은 몇 퍼센트일까?", answer:34, source:"Pew Research Center, 2022" },
  { id:135, text:"아이폰보다 안드로이드가 좋다고 답한 미국인은 몇 퍼센트일까?", answer:42, source:"Consumer Technology Association, 2023" },
  { id:136, text:"밝은 화면보다 다크 모드가 좋다고 답한 사람은 몇 퍼센트일까?", answer:58, source:"UX Design Research Institute, 2023" },
  { id:137, text:"프로 스포츠 경기를 직접 보러 간 적이 한 번도 없는 미국인은 몇 퍼센트일까?", answer:48, source:"Sports Marketing Research Institute, 2023" },
  { id:138, text:"일하는 척하면서 사실 아무것도 안 한 적 있다고 인정한 사람은 몇 퍼센트일까?", answer:89, source:"Harvard Business Review Workplace Study, 2022" },
  ],
};
