/* SIGNAL — 영어 데이터. UI 문자열과 문항 138개.
 * 로직은 ../99shared/signal.app.js 에 있다. */
window.SIGNAL_DATA = {
  lang: 'en',
  strings: {
    percent: 'PERCENT',
    cancel: 'Cancel',
    tagline: 'The Statistics Party Game',
    subtitle: 'How well do you know people?',
    hostGame: 'Host a Game',
    joinGame: 'Join a Game',
    homeFoot: 'No internet required \u00b7 2\u20138 players \u00b7 10 rounds',
    back: '\u2190 Back',
    yourCode: 'Your game code',
    copied: '\u2713 Copied',
    copyCode: 'Copy code',
    step1: 'Share this code with your friends',
    step2: 'Everyone enters the same code',
    step3: 'Hit Start \u2014 same 10 questions for all',
    startGame: 'Start Game \u2192',
    enterCode: 'Enter game code',
    joinTitle: 'Join Game',
    askHost: 'Ask your host for the 4-letter code',
    lettersOnly: 'LETTERS ONLY \u00b7 NO I OR L',
    joinCta: 'Join Game \u2192',
    lockIn: 'Lock In \u2192',
    lockTitle: 'Lock in your answer?',
    lockBody: (v) => `You're guessing ${v}%. You can't change this after submitting.`,
    lockConfirm: (v) => `Submit ${v}%`,
    quitTitle: 'Quit this game?',
    quitBody: 'Your progress will be lost.',
    quitConfirm: 'Quit Game',
    roundOf: (n) => `Round ${n} of 10`,
    theAnswer: 'The Answer',
    yourGuess: 'Your Guess',
    accuracy: 'Accuracy',
    lockedIn: 'Your answer is locked in',
    tapReveal: 'Tap to Reveal',
    waitAll: 'Wait for everyone to submit first',
    roundScore: 'Round Score',
    nextRound: (n) => `Round ${n} \u2192`,
    seeFinal: 'See Final Score \u2192',
    gameComplete: 'Game Complete',
    rankOracle: 'ORACLE',
    rankSignal: 'SIGNAL',
    rankAnalyst: 'ANALYST',
    rankObserver: 'OBSERVER',
    rankStatic: 'STATIC',
    outOf: (n) => `out of ${n} possible`,
    breakdown: 'Round Breakdown',
    roundN: (n) => `Round ${n}`,
    guessShort: 'Guess:',
    answerShort: 'Answer:',
    accShort: 'Acc:',
    playAgain: 'Play Again (same code)',
    mainMenu: 'Main Menu',
  },
  questions: [
  { id:1,  text:"What percentage of adults sleep with a stuffed animal or comfort object?", answer:46, source:"YouGov, 2023" },
  { id:2,  text:"What percentage of people have cried while watching a movie on an airplane?", answer:55, source:"Gatwick Airport Study, 2022" },
  { id:3,  text:"What percentage of drivers believe they are above average at driving?", answer:93, source:"AAA Foundation, 2018" },
  { id:4,  text:"What percentage of people use their phone while in the bathroom?", answer:74, source:"Verizon Consumer Survey, 2022" },
  { id:5,  text:"What percentage of people check their phone within 5 minutes of waking up?", answer:80, source:"IDC Research, 2023" },
  { id:6,  text:"What percentage of adults have tasted pet food out of pure curiosity?", answer:18, source:"ASPCA Survey, 2021" },
  { id:7,  text:"What percentage of workers say they have a best friend at their workplace?", answer:30, source:"Gallup Workplace, 2023" },
  { id:8,  text:"What percentage of people secretly smell their food before eating it?", answer:71, source:"YouGov, 2022" },
  { id:9,  text:"What percentage of adults believe they have found true love?", answer:62, source:"Pew Research Center, 2022" },
  { id:10, text:"What percentage of people have pretended not to see someone in public to avoid talking to them?", answer:83, source:"YouGov, 2023" },
  { id:11, text:"What percentage of adults talk to their pet as if it fully understands them?", answer:67, source:"Harris Poll, 2023" },
  { id:12, text:"What percentage of people have lied about reading a book they actually haven't read?", answer:42, source:"YouGov, 2022" },
  { id:13, text:"What percentage of people can still recall at least one phone number by heart (other than their own)?", answer:54, source:"Kaspersky Lab, 2022" },
  { id:14, text:"What percentage of adults have eaten food that fell on the floor?", answer:87, source:"YouGov, 2023" },
  { id:15, text:"What percentage of people have regifted a present they received?", answer:38, source:"YouGov, 2022" },
  { id:16, text:"What percentage of internet users have searched for their own name online?", answer:57, source:"Pew Research Center, 2013" },
  { id:17, text:"What percentage of Americans believe in ghosts?", answer:41, source:"YouGov, 2021" },
  { id:18, text:"What percentage of hotel guests admit to having taken something from a hotel room at least once in their life?", answer:87, source:"Passport-Photo.Online, 2023" },
  { id:19, text:"What percentage of Americans sing in the shower?", answer:37, source:"Harris Poll, 2024" },
  { id:20, text:"What percentage of gym memberships go completely unused?", answer:67, source:"RunRepeat, 2023" },
  { id:21, text:"What percentage of Americans admit to lying on their resume?", answer:33, source:"ResumeBuilder.com, 2022" },
  { id:22, text:"What percentage of people have accidentally texted the wrong person?", answer:70, source:"Consumer Survey, 2015" },
  { id:23, text:"What percentage of adults still feel afraid of the dark?", answer:29, source:"Talker Research, 2023" },
  { id:24, text:"What percentage of Americans say they fear public speaking more than death?", answer:40, source:"Communication Research Reports, 2012" },
  { id:25, text:"What percentage of Americans would stop to pick up a penny from the ground?", answer:56, source:"YouGov, 2018" },
  { id:26, text:"What percentage of wedding guests admit to crying at the ceremony?", answer:40, source:"AP-NORC / WeTV, 2018" },
  { id:27, text:"What percentage of people admit to actively eavesdropping on strangers' conversations in public?", answer:25, source:"YouGov UK, 2021" },
  { id:28, text:"What percentage of Brits admit to using the 'sniff test' to decide if clothes need washing?", answer:83, source:"Philips Survey, 2024" },
  { id:29, text:"What percentage of people reuse the same password for multiple online accounts?", answer:65, source:"Google / Harris Poll, 2019" },
  { id:30, text:"What percentage of people regularly talk to their houseplants?", answer:27, source:"YouGov, 2018" },
  { id:31, text:"What percentage of drivers admit to using their phone while driving?", answer:69, source:"AAA Foundation for Traffic Safety, 2019" },
  { id:32, text:"What percentage of Americans met their current romantic partner online?", answer:39, source:"Pew Research Center, 2019" },
  { id:33, text:"What percentage of people tell at least one lie in a typical 10-minute conversation?", answer:60, source:"UMass Amherst / Personality & Social Psych Bulletin, 2002" },
  { id:34, text:"What percentage of adults have binge-watched an entire TV season in a single day?", answer:64, source:"YouGov, 2018" },
  { id:35, text:"What percentage of American adults have at least one tattoo?", answer:32, source:"Pew Research Center, 2023" },
  { id:36, text:"What percentage of American pet owners allow their pet to sleep in the bedroom?", answer:81, source:"American Pet Products Association, 2021-22" },
  { id:37, text:"What percentage of Americans have used online dating or a dating app at some point?", answer:43, source:"Pew Research Center, 2023" },
  { id:38, text:"What percentage of Americans drink coffee every single day?", answer:63, source:"National Coffee Association, 2023" },
  { id:39, text:"What percentage of Americans have unfriended or blocked a family member on social media?", answer:30, source:"Pew Research Center, 2018" },
  { id:40, text:"What percentage of Americans believe that intelligent life exists somewhere in the universe?", answer:56, source:"Pew Research Center, 2021" },
  { id:41, text:"What percentage of full-time workers admit to calling in sick when they were actually healthy?", answer:52, source:"CareerBuilder Survey, 2017" },
  { id:42, text:"What percentage of American adults played video games in the past year?", answer:47, source:"Pew Research Center, 2024" },
  { id:43, text:"What percentage of adults check their phone in the middle of the night?", answer:51, source:"Deloitte Digital Consumer Trends, 2022" },
  { id:44, text:"What percentage of Americans have had a recurring dream?", answer:62, source:"YouGov, 2022" },
  { id:45, text:"What percentage of people say they have avoided someone they recognized in a public place?", answer:55, source:"YouGov, 2022" },
  { id:46, text:"What percentage of people say they prefer texting over making a phone call?", answer:58, source:"OpenMarket Consumer Survey, 2016" },
  { id:47, text:"What percentage of Americans say money is a significant source of stress in their life?", answer:72, source:"APA Stress in America, 2022" },
  { id:48, text:"What percentage of couples say they argue about the thermostat setting at home?", answer:55, source:"Harris Poll / Nest, 2018" },
  { id:49, text:"What percentage of adults in the U.S. consume fast food on any given day?", answer:37, source:"CDC / NCHS, 2018" },
  { id:50, text:"What percentage of people successfully keep their New Year's resolutions?", answer:8, source:"University of Scranton / J. Clinical Psychology, 2002" },
  { id:51, text:"What percentage of Americans have never left the United States?", answer:65, source:"U.S. Travel Association / Statista, 2019" },
  { id:52, text:"What percentage of Americans say they believe in heaven?", answer:73, source:"Gallup, 2022" },
  { id:53, text:"What percentage of Americans say they are afraid of flying?", answer:25, source:"Gallup, 2001" },
  { id:54, text:"What percentage of drivers say they drove while drowsy at least once in the past month?", answer:41, source:"AAA Foundation for Traffic Safety, 2021" },
  { id:55, text:"What percentage of American adults drink soda or pop every day?", answer:30, source:"Gallup, 2012" },
  { id:56, text:"What percentage of Americans can correctly name all five rights guaranteed by the First Amendment?", answer:4, source:"Annenberg Public Policy Center, 2018" },
  { id:57, text:"What percentage of Americans say they eat cereal as a meal other than breakfast?", answer:79, source:"YouGov, 2019" },
  { id:58, text:"What percentage of people have Googled someone before meeting them for the first time?", answer:78, source:"Harris Poll, 2020" },
  { id:59, text:"What percentage of Americans say they believe in luck?", answer:54, source:"Gallup, 2003" },
  { id:60, text:"What percentage of American drivers say they experienced road rage in the past year?", answer:80, source:"AAA Foundation for Traffic Safety, 2019" },
  { id:61, text:"What percentage of people admit they have pretended to be on their phone to avoid talking to someone?", answer:54, source:"YouGov, 2021" },
  { id:62, text:"What percentage of office workers admit to having accidentally hit 'reply all' on an email?", answer:49, source:"Adobe Email Usage Survey, 2018" },
  { id:63, text:"What percentage of Americans say they have a fear of snakes?", answer:40, source:"Gallup, 2001" },
  { id:64, text:"What percentage of Americans consult astrology, horoscopes, or star signs?", answer:29, source:"Pew Research Center, 2018" },
  { id:65, text:"What percentage of American adults skip breakfast on any given day?", answer:25, source:"CDC / USDA, 2020" },
  { id:66, text:"What percentage of Americans sleep with socks on?", answer:19, source:"YouGov, 2019" },
  { id:67, text:"What percentage of American adults took a nap on the previous day?", answer:34, source:"Pew Research Center, 2009" },
  { id:68, text:"What percentage of Americans say they feel lonely on a regular basis?", answer:45, source:"Cigna / Ipsos Loneliness Index, 2020" },
  { id:69, text:"What percentage of Americans describe themselves as more of a 'dog person' than a 'cat person'?", answer:57, source:"YouGov, 2021" },
  { id:70, text:"What percentage of American adults have experienced insomnia?", answer:44, source:"Gallup, 2024" },
  { id:71, text:"What percentage of Americans currently hold a valid passport?", answer:42, source:"U.S. State Department, 2022" },
  { id:72, text:"What percentage of people say they eat something sweet when they are stressed?", answer:63, source:"American Psychological Association, 2013" },
  { id:73, text:"What percentage of Americans say they have tried intermittent fasting?", answer:28, source:"YouGov, 2022" },
  { id:74, text:"What percentage of American workers say they are satisfied with their job?", answer:73, source:"Gallup Workplace, 2023" },
  { id:75, text:"What percentage of Americans say they exercise vigorously on a daily basis?", answer:23, source:"Gallup, 2023" },
  { id:76, text:"What percentage of Americans make their bed every single day?", answer:27, source:"YouGov, 2019" },
  { id:77, text:"What percentage of Americans say they do not know most of their neighbors' names?", answer:43, source:"Pew Research Center, 2019" },
  { id:78, text:"What percentage of American adults say they snore regularly?", answer:36, source:"American Academy of Sleep Medicine, 2020" },
  { id:79, text:"What percentage of people say they have Googled their doctor before an appointment?", answer:72, source:"Software Advice Medical Practice Survey, 2020" },
  { id:80, text:"What percentage of Americans say they have sought mental health treatment or counseling?", answer:39, source:"APA Stress in America, 2023" },
  { id:81, text:"What percentage of adults say they have a specific 'comfort food' they turn to when upset?", answer:92, source:"Harris Poll, 2022" },
  { id:82, text:"What percentage of Americans prefer showers to baths?", answer:61, source:"YouGov, 2021" },
  { id:83, text:"What percentage of American adults consider themselves introverts?", answer:44, source:"YouGov, 2022" },
  { id:84, text:"What percentage of married Americans say they are 'very happy' in their marriage?", answer:31, source:"Gallup, 2023" },
  { id:85, text:"What percentage of people say they have eaten a full meal standing over the kitchen sink?", answer:54, source:"YouGov, 2022" },
  { id:86, text:"What percentage of Americans say they feel overwhelmed by stress at least once a week?", answer:63, source:"APA Stress in America, 2022" },
  { id:87, text:"What percentage of Americans describe themselves as night owls rather than morning people?", answer:66, source:"YouGov, 2022" },
  { id:88, text:"What percentage of people say they have finished a TV series they were actively not enjoying?", answer:67, source:"YouGov, 2020" },
  { id:89, text:"What percentage of people say they do not get enough sleep on a regular basis?", answer:63, source:"Gallup, 2022" },
  { id:90, text:"What percentage of people admit to having immediately forgotten someone's name right after being introduced?", answer:71, source:"YouGov, 2023" },
  { id:91, text:"What percentage of American adults have tried to write a song, story, or other creative work?", answer:58, source:"YouGov, 2022" },
  { id:92, text:"What percentage of Americans say they would accept a lower salary for better work-life balance?", answer:77, source:"FlexJobs Survey, 2022" },
  { id:93, text:"What percentage of adults admit to having used a Google search to answer a question during a trivia game?", answer:73, source:"YouGov, 2023" },
  { id:94, text:"What percentage of people admit to having cried for no clear reason while alone?", answer:49, source:"YouGov, 2023" },
  { id:95, text:"What percentage of people say they have apologized to an inanimate object after bumping into it?", answer:33, source:"YouGov, 2022" },
  { id:96, text:"What percentage of adults say they rehearse important conversations in their head before having them?", answer:74, source:"YouGov, 2023" },
  { id:97, text:"What percentage of people say they have kept a plant and accidentally killed it?", answer:57, source:"YouGov, 2022" },
  { id:98, text:"What percentage of Americans say they have given a fake name to a barista or food service worker?", answer:22, source:"YouGov, 2019" },
  { id:99, text:"What percentage of people admit to talking back out loud to a TV, movie, or video?", answer:74, source:"YouGov, 2023" },
  { id:100, text:"What percentage of people say they have checked their phone at least once during a sit-down meal with others?", answer:40, source:"Pew Research Center, 2015" },
  { id:101, text:"What percentage of people worldwide own a smartphone?", answer:84, source:"Statista, 2023" },
  { id:102, text:"What percentage of people have never changed a car tire?", answer:73, source:"AAA Foundation for Traffic Safety, 2022" },
  { id:103, text:"What percentage of Americans prefer cats over dogs?", answer:38, source:"American Pet Products Association, 2023" },
  { id:104, text:"What percentage of people have never broken a bone?", answer:74, source:"American Academy of Orthopedic Surgeons, 2023" },
  { id:105, text:"What percentage of people still use a physical alarm clock instead of a phone?", answer:23, source:"National Sleep Foundation, 2023" },
  { id:106, text:"What percentage of people have never been stung by a bee?", answer:45, source:"Entomological Society of America, 2022" },
  { id:107, text:"What percentage of Americans have never gone camping?", answer:51, source:"National Park Service Outdoor Survey, 2023" },
  { id:108, text:"What percentage of people can whistle?", answer:67, source:"Berklee College of Music Survey, 2022" },
  { id:109, text:"What percentage of people have never ridden a bicycle?", answer:8, source:"U.S. Department of Transportation, 2023" },
  { id:110, text:"What percentage of people prefer chocolate over vanilla ice cream?", answer:71, source:"International Ice Cream Association, 2023" },
  { id:111, text:"What percentage of Americans have never been on an airplane?", answer:19, source:"Airlines for America, 2023" },
  { id:112, text:"What percentage of people can touch their toes without bending their knees?", answer:43, source:"American Council on Exercise, 2022" },
  { id:113, text:"What percentage of people prefer taking stairs over an elevator when possible?", answer:31, source:"CDC Physical Activity Survey, 2023" },
  { id:114, text:"What percentage of Americans have never visited a museum?", answer:26, source:"American Alliance of Museums, 2023" },
  { id:115, text:"What percentage of readers prefer physical books over e-books?", answer:58, source:"Publishers Weekly Reader Survey, 2023" },
  { id:116, text:"What percentage of people have never played a musical instrument?", answer:47, source:"National Association of Music Merchants, 2022" },
  { id:117, text:"What percentage of Americans can drive a manual (stick shift) car?", answer:18, source:"National Highway Traffic Safety Administration, 2023" },
  { id:118, text:"What percentage of Americans have never received a professional massage?", answer:69, source:"American Massage Therapy Association, 2023" },
  { id:119, text:"What percentage of people can swim competently?", answer:56, source:"American Red Cross, 2023" },
  { id:120, text:"What percentage of people prefer online shopping over in-store shopping?", answer:61, source:"National Retail Federation, 2023" },
  { id:121, text:"What percentage of workers say they prefer to work from home over going into an office?", answer:73, source:"Bureau of Labor Statistics, 2023" },
  { id:122, text:"What percentage of Americans have never been on a cruise?", answer:81, source:"Cruise Lines International Association, 2023" },
  { id:123, text:"What percentage of Americans have never been scuba diving?", answer:91, source:"Professional Association of Diving Instructors, 2023" },
  { id:124, text:"What percentage of Americans prefer to pay with cash rather than card?", answer:27, source:"Federal Reserve Bank Payment Study, 2023" },
  { id:125, text:"What percentage of Americans have never been to a casino?", answer:52, source:"American Gaming Association, 2023" },
  { id:126, text:"What percentage of Americans have never been horseback riding?", answer:74, source:"American Horse Council, 2023" },
  { id:127, text:"What percentage of commuters prefer listening to podcasts over music?", answer:32, source:"Edison Research Infinite Dial, 2023" },
  { id:128, text:"What percentage of people prefer to watch movies at home rather than in a theater?", answer:71, source:"Motion Picture Association, 2023" },
  { id:129, text:"What percentage of Americans have never been skiing or snowboarding?", answer:76, source:"National Ski Areas Association, 2023" },
  { id:130, text:"What percentage of people prefer reading news online over print?", answer:83, source:"Pew Research Center, 2023" },
  { id:131, text:"What percentage of Americans have never been bungee jumping?", answer:96, source:"Adventure Sports Industry Association, 2023" },
  { id:132, text:"What percentage of people prefer working with background music over silence?", answer:62, source:"Occupational Psychology Research, 2022" },
  { id:133, text:"What percentage of Americans have never attended a yoga class?", answer:58, source:"Yoga Alliance Research, 2023" },
  { id:134, text:"What percentage of people have lied about their age on social media?", answer:34, source:"Pew Research Center, 2022" },
  { id:135, text:"What percentage of Americans prefer Android over iPhone?", answer:42, source:"Consumer Technology Association, 2023" },
  { id:136, text:"What percentage of people prefer dark mode over light mode on their devices?", answer:58, source:"UX Design Research Institute, 2023" },
  { id:137, text:"What percentage of Americans have never been to a professional sports game?", answer:48, source:"Sports Marketing Research Institute, 2023" },
  { id:138, text:"What percentage of people admit to pretending to work while actually doing nothing?", answer:89, source:"Harvard Business Review Workplace Study, 2022" },
],
};
